- name: Install todo app on new web servers
  hosts: webservers
  remote_user: ec2-user

  vars_prompt:
    - name: secretKey
      prompt: What is the Flask secret key?

    - name: db_connection_string
      prompt: What is the database connection string?

    - name: database_name
      prompt: What is the database name?

  tasks:
  - name: Install git & python
    yum:
      name:
        - git
        - python3
      state: latest
    become: yes

  - name: Install poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      creates: ~/.local/bin/poetry

  - name: Create app folder
    ansible.builtin.file:
      path: /var/todo_app
      state: directory
      mode: '755'
    become: yes

  - name: Set git repo as safe
    ansible.builtin.shell: source ~/.bash_profile && (git config --global --add safe.directory /var/todo_app)

  - name: Git clone todo app main branch
    ansible.builtin.git:
      repo: https://github.com/emilies03/To-Do-App.git
      dest: /var/todo_app
      single_branch: yes
      version: main

  - name: Install poetry dependencies
    ansible.builtin.shell: 
      cmd: source ~/.bash_profile && poetry install
      chdir: /var/todo_app

  - name: Copy accross dotenv template file
    ansible.builtin.template:
      src: ~/.env.j2
      dest: /var/todo_app/.env

  - name: Copy service file
    ansible.builtin.copy:
      src: ~/todo_app.service
      dest: /etc/systemd/system/todo_app.service
      mode: '755'
    become: yes    

  - name: Start the to_do app
    ansible.builtin.systemd:
      name: todo_app.service
      state: started
    become: yes