name: Continuous Integration
on:
  pull_request:
    types: [opened, synchronize]
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker container 
      run: docker build --target test --tag todo-app:test .
    - name: run docker tests
      run: docker run todo-app:test